version: '3.8'

services:
  redis:
    hostname: redis
    env_file:
      - .env
    image: redis:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/data
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_PORT}
    networks:
      - redis-network
    restart: always

  torch-serve:
    hostname: torch-serve
    env_file:
      - .env
    build:
      context: ./torch-serve
    ports:
      - ${TORCH_SERVE_EXTERNAL_INFERENCE_PORT}:${TORCH_SERVE_INFERENCE_PORT}
    networks:
      - torch-serve-network
    stdin_open: true
    tty: true
    restart: on-failure

  fast-api1:
    hostname: fast-api1
    depends_on:
      - redis
      - torch-serve
    env_file:
      - .env
    # Path to Dockerfile relative to docker-compose.yml
    build:
      context: ./fast-api
    volumes:
      - ./fast-api:/fast-api
      - ./data:/fast-api/data:ro # TODO: нужно ли так писать, если уже смонтирован ./fast-api со всеми вложенными папками?
    ports:
      - "5032:3032"
    networks:
      - redis-network
      - torch-serve-network
      - fast-api-network
    stdin_open: true
    tty: true
    restart: on-failure

  fast-api2:
    hostname: fast-api2
    depends_on:
      - redis
      - torch-serve
    env_file:
      - .env
    # Path to Dockerfile relative to docker-compose.yml
    build:
      context: ./fast-api
    volumes:
      - ./fast-api:/fast-api
      - ./data:/fast-api/data:ro # TODO: нужно ли так писать, если уже смонтирован ./fast-api со всеми вложенными папками?
    ports:
      - "5012:3012"
    networks:
      - redis-network
      - torch-serve-network
      - fast-api-network
    stdin_open: true
    tty: true
    restart: on-failure

  fast-api3:
    hostname: fast-api3
    depends_on:
      - redis
      - torch-serve
    env_file:
      - .env
    # Path to Dockerfile relative to docker-compose.yml
    build:
      context: ./fast-api
    volumes:
      - ./fast-api:/fast-api
      - ./data:/fast-api/data:ro # TODO: нужно ли так писать, если уже смонтирован ./fast-api со всеми вложенными папками?
    ports:
      - "5022:3022"
    networks:
      - redis-network
      - torch-serve-network
      - fast-api-network
    stdin_open: true
    tty: true
    restart: on-failure

  nginx:
    hostname: nginx
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - ${NGINX_EXTERNAL_PORT}:${NGINX_PORT}
    networks:
      - fast-api-network
    restart: always

volumes:
  redis:
    driver: local

networks:
  spring-boot-network:
  redis-network:
  torch-serve-network:
  fast-api-network:
