version: '3.8'

services:
  redis:
    image:
  fast-api:
    depends_on:
      - redis
    env_file:
      - .env
    # Path to Dockerfile relative to docker-compose.yml
    build:
      context: ./fast-api
    volumes:
      - ./fast-api:/fast-api
      - ./fast-api/data:/fast-api/data:ro # TODO: нужно ли так писать, если уже смонтирован ./fast-api со всеми вложенными папками?
    ports:
      - ${FAST_API_EXTERNAL_PORT}:${FAST_API_PORT}
    networks:
      - fast-api-network
    stdin_open: true
    tty: true
    restart: on-failure
