version: '3.8'

services:
  redis:
    env_file:
      - .env
    image: redis:7.2
    entrypoint:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/data
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_PORT}
    networks:
      - redis-api
    restart: always

  torch-serve:
    env_file:
      - .env
    build:
      context: ./torch-serve
    ports:
      - ${TORCH_SERVE_EXTERNAL_API_PORT}:${TORCH_SERVE_API_PORT}
    networks:
      - torch-serve-api
    stdin_open: true
    tty: true
    restart: on-failure

  fast-api:
    depends_on:
      - redis
      - torch-serve
    env_file:
      - .env
    # Path to Dockerfile relative to docker-compose.yml
    build:
      context: ./fast-api
    volumes:
      - ./fast-api:/fast-api
      - ./fast-api/data:/fast-api/data:ro # TODO: нужно ли так писать, если уже смонтирован ./fast-api со всеми вложенными папками?
    ports:
      - ${FAST_API_EXTERNAL_PORT}:${FAST_API_PORT}
    networks:
      - redis-api
      - torch-serve-api
      - fast-api-network
    stdin_open: true
    tty: true
    restart: on-failure

volumes:
  redis:
    driver: local
